// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permit.proto

package permit

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePermitRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	SharerID             string   `protobuf:"bytes,2,opt,name=sharerID,proto3" json:"sharerID,omitempty"`
	Users                []*User  `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Classification       string   `protobuf:"bytes,4,opt,name=classification,proto3" json:"classification,omitempty"`
	Info                 string   `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	Approvers            []string `protobuf:"bytes,6,rep,name=approvers,proto3" json:"approvers,omitempty"`
	FileName             string   `protobuf:"bytes,7,opt,name=fileName,proto3" json:"fileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePermitRequest) Reset()         { *m = CreatePermitRequest{} }
func (m *CreatePermitRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePermitRequest) ProtoMessage()    {}
func (*CreatePermitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{0}
}

func (m *CreatePermitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePermitRequest.Unmarshal(m, b)
}
func (m *CreatePermitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePermitRequest.Marshal(b, m, deterministic)
}
func (m *CreatePermitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePermitRequest.Merge(m, src)
}
func (m *CreatePermitRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePermitRequest.Size(m)
}
func (m *CreatePermitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePermitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePermitRequest proto.InternalMessageInfo

func (m *CreatePermitRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *CreatePermitRequest) GetSharerID() string {
	if m != nil {
		return m.SharerID
	}
	return ""
}

func (m *CreatePermitRequest) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *CreatePermitRequest) GetClassification() string {
	if m != nil {
		return m.Classification
	}
	return ""
}

func (m *CreatePermitRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *CreatePermitRequest) GetApprovers() []string {
	if m != nil {
		return m.Approvers
	}
	return nil
}

func (m *CreatePermitRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type CreatePermitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePermitResponse) Reset()         { *m = CreatePermitResponse{} }
func (m *CreatePermitResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePermitResponse) ProtoMessage()    {}
func (*CreatePermitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{2}
}

func (m *CreatePermitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePermitResponse.Unmarshal(m, b)
}
func (m *CreatePermitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePermitResponse.Marshal(b, m, deterministic)
}
func (m *CreatePermitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePermitResponse.Merge(m, src)
}
func (m *CreatePermitResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePermitResponse.Size(m)
}
func (m *CreatePermitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePermitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePermitResponse proto.InternalMessageInfo

type UpdatePermitStatusRequest struct {
	ReqID                string   `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePermitStatusRequest) Reset()         { *m = UpdatePermitStatusRequest{} }
func (m *UpdatePermitStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePermitStatusRequest) ProtoMessage()    {}
func (*UpdatePermitStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{3}
}

func (m *UpdatePermitStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePermitStatusRequest.Unmarshal(m, b)
}
func (m *UpdatePermitStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePermitStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePermitStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePermitStatusRequest.Merge(m, src)
}
func (m *UpdatePermitStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePermitStatusRequest.Size(m)
}
func (m *UpdatePermitStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePermitStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePermitStatusRequest proto.InternalMessageInfo

func (m *UpdatePermitStatusRequest) GetReqID() string {
	if m != nil {
		return m.ReqID
	}
	return ""
}

func (m *UpdatePermitStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpdatePermitStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePermitStatusResponse) Reset()         { *m = UpdatePermitStatusResponse{} }
func (m *UpdatePermitStatusResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePermitStatusResponse) ProtoMessage()    {}
func (*UpdatePermitStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{4}
}

func (m *UpdatePermitStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePermitStatusResponse.Unmarshal(m, b)
}
func (m *UpdatePermitStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePermitStatusResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePermitStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePermitStatusResponse.Merge(m, src)
}
func (m *UpdatePermitStatusResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePermitStatusResponse.Size(m)
}
func (m *UpdatePermitStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePermitStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePermitStatusResponse proto.InternalMessageInfo

type GetPermitByFileIDRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPermitByFileIDRequest) Reset()         { *m = GetPermitByFileIDRequest{} }
func (m *GetPermitByFileIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetPermitByFileIDRequest) ProtoMessage()    {}
func (*GetPermitByFileIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{5}
}

func (m *GetPermitByFileIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermitByFileIDRequest.Unmarshal(m, b)
}
func (m *GetPermitByFileIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermitByFileIDRequest.Marshal(b, m, deterministic)
}
func (m *GetPermitByFileIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermitByFileIDRequest.Merge(m, src)
}
func (m *GetPermitByFileIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetPermitByFileIDRequest.Size(m)
}
func (m *GetPermitByFileIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermitByFileIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermitByFileIDRequest proto.InternalMessageInfo

func (m *GetPermitByFileIDRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

type GetPermitByFileIDResponse struct {
	UserStatus           []*UserStatus `protobuf:"bytes,1,rep,name=userStatus,proto3" json:"userStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPermitByFileIDResponse) Reset()         { *m = GetPermitByFileIDResponse{} }
func (m *GetPermitByFileIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetPermitByFileIDResponse) ProtoMessage()    {}
func (*GetPermitByFileIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{6}
}

func (m *GetPermitByFileIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermitByFileIDResponse.Unmarshal(m, b)
}
func (m *GetPermitByFileIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermitByFileIDResponse.Marshal(b, m, deterministic)
}
func (m *GetPermitByFileIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermitByFileIDResponse.Merge(m, src)
}
func (m *GetPermitByFileIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetPermitByFileIDResponse.Size(m)
}
func (m *GetPermitByFileIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermitByFileIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermitByFileIDResponse proto.InternalMessageInfo

func (m *GetPermitByFileIDResponse) GetUserStatus() []*UserStatus {
	if m != nil {
		return m.UserStatus
	}
	return nil
}

type HasPermitRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasPermitRequest) Reset()         { *m = HasPermitRequest{} }
func (m *HasPermitRequest) String() string { return proto.CompactTextString(m) }
func (*HasPermitRequest) ProtoMessage()    {}
func (*HasPermitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{7}
}

func (m *HasPermitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasPermitRequest.Unmarshal(m, b)
}
func (m *HasPermitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasPermitRequest.Marshal(b, m, deterministic)
}
func (m *HasPermitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasPermitRequest.Merge(m, src)
}
func (m *HasPermitRequest) XXX_Size() int {
	return xxx_messageInfo_HasPermitRequest.Size(m)
}
func (m *HasPermitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HasPermitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HasPermitRequest proto.InternalMessageInfo

func (m *HasPermitRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *HasPermitRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type HasPermitResponse struct {
	HasPermit            bool     `protobuf:"varint,1,opt,name=hasPermit,proto3" json:"hasPermit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasPermitResponse) Reset()         { *m = HasPermitResponse{} }
func (m *HasPermitResponse) String() string { return proto.CompactTextString(m) }
func (*HasPermitResponse) ProtoMessage()    {}
func (*HasPermitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{8}
}

func (m *HasPermitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasPermitResponse.Unmarshal(m, b)
}
func (m *HasPermitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasPermitResponse.Marshal(b, m, deterministic)
}
func (m *HasPermitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasPermitResponse.Merge(m, src)
}
func (m *HasPermitResponse) XXX_Size() int {
	return xxx_messageInfo_HasPermitResponse.Size(m)
}
func (m *HasPermitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HasPermitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HasPermitResponse proto.InternalMessageInfo

func (m *HasPermitResponse) GetHasPermit() bool {
	if m != nil {
		return m.HasPermit
	}
	return false
}

type UserStatus struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStatus) Reset()         { *m = UserStatus{} }
func (m *UserStatus) String() string { return proto.CompactTextString(m) }
func (*UserStatus) ProtoMessage()    {}
func (*UserStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{9}
}

func (m *UserStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStatus.Unmarshal(m, b)
}
func (m *UserStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStatus.Marshal(b, m, deterministic)
}
func (m *UserStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStatus.Merge(m, src)
}
func (m *UserStatus) XXX_Size() int {
	return xxx_messageInfo_UserStatus.Size(m)
}
func (m *UserStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UserStatus proto.InternalMessageInfo

func (m *UserStatus) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type PermitObject struct {
	ReqID                string   `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	FileID               string   `protobuf:"bytes,2,opt,name=fileID,proto3" json:"fileID,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermitObject) Reset()         { *m = PermitObject{} }
func (m *PermitObject) String() string { return proto.CompactTextString(m) }
func (*PermitObject) ProtoMessage()    {}
func (*PermitObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_727fd833651e2ed7, []int{10}
}

func (m *PermitObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermitObject.Unmarshal(m, b)
}
func (m *PermitObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermitObject.Marshal(b, m, deterministic)
}
func (m *PermitObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermitObject.Merge(m, src)
}
func (m *PermitObject) XXX_Size() int {
	return xxx_messageInfo_PermitObject.Size(m)
}
func (m *PermitObject) XXX_DiscardUnknown() {
	xxx_messageInfo_PermitObject.DiscardUnknown(m)
}

var xxx_messageInfo_PermitObject proto.InternalMessageInfo

func (m *PermitObject) GetReqID() string {
	if m != nil {
		return m.ReqID
	}
	return ""
}

func (m *PermitObject) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *PermitObject) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PermitObject) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*CreatePermitRequest)(nil), "permit.CreatePermitRequest")
	proto.RegisterType((*User)(nil), "permit.User")
	proto.RegisterType((*CreatePermitResponse)(nil), "permit.CreatePermitResponse")
	proto.RegisterType((*UpdatePermitStatusRequest)(nil), "permit.UpdatePermitStatusRequest")
	proto.RegisterType((*UpdatePermitStatusResponse)(nil), "permit.UpdatePermitStatusResponse")
	proto.RegisterType((*GetPermitByFileIDRequest)(nil), "permit.GetPermitByFileIDRequest")
	proto.RegisterType((*GetPermitByFileIDResponse)(nil), "permit.GetPermitByFileIDResponse")
	proto.RegisterType((*HasPermitRequest)(nil), "permit.HasPermitRequest")
	proto.RegisterType((*HasPermitResponse)(nil), "permit.HasPermitResponse")
	proto.RegisterType((*UserStatus)(nil), "permit.UserStatus")
	proto.RegisterType((*PermitObject)(nil), "permit.PermitObject")
}

func init() { proto.RegisterFile("permit.proto", fileDescriptor_727fd833651e2ed7) }

var fileDescriptor_727fd833651e2ed7 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0x4e, 0x62, 0xea, 0x21, 0xaa, 0xe8, 0x50, 0x45, 0x1b, 0x37, 0x87, 0x74, 0x0f, 0x28,
	0xa7, 0x4a, 0xa4, 0x57, 0x4e, 0xa1, 0x02, 0x22, 0x24, 0x8a, 0x8c, 0x7a, 0x41, 0x42, 0xc8, 0x4d,
	0x36, 0xea, 0x22, 0x37, 0x76, 0x77, 0x37, 0x48, 0xfc, 0x4f, 0xfe, 0x01, 0x7f, 0x04, 0xed, 0x67,
	0x4c, 0x63, 0x07, 0x6e, 0x79, 0x33, 0x3b, 0x6f, 0x3e, 0xde, 0x73, 0x60, 0x50, 0x31, 0x71, 0xcf,
	0xd5, 0x45, 0x25, 0x4a, 0x55, 0x62, 0x6c, 0x11, 0xfd, 0xdd, 0x81, 0x17, 0x6f, 0x04, 0xcb, 0x15,
	0xfb, 0x64, 0x02, 0x19, 0x7b, 0xd8, 0x32, 0xa9, 0x70, 0x08, 0xf1, 0x9a, 0x17, 0x6c, 0x71, 0x45,
	0x3a, 0x93, 0xce, 0x34, 0xc9, 0x1c, 0xc2, 0x14, 0x8e, 0xe4, 0x5d, 0x2e, 0x98, 0x58, 0x5c, 0x91,
	0xc8, 0x64, 0x02, 0x46, 0x0a, 0xfd, 0xad, 0x64, 0x42, 0x92, 0xee, 0xa4, 0x3b, 0x7d, 0x36, 0x1b,
	0x5c, 0xb8, 0x8e, 0x37, 0x92, 0x89, 0xcc, 0xa6, 0xf0, 0x25, 0x1c, 0x2f, 0x8b, 0x5c, 0x4a, 0xbe,
	0xe6, 0xcb, 0x5c, 0xf1, 0x72, 0x43, 0x7a, 0x86, 0xe5, 0x51, 0x14, 0x11, 0x7a, 0x7c, 0xb3, 0x2e,
	0x49, 0xdf, 0x64, 0xcd, 0x6f, 0x1c, 0x43, 0x92, 0x57, 0x95, 0x28, 0x7f, 0xe8, 0x1e, 0xf1, 0xa4,
	0x3b, 0x4d, 0xb2, 0x5d, 0x40, 0x4f, 0xa6, 0x67, 0xfc, 0x98, 0xdf, 0x33, 0xf2, 0xd4, 0x4e, 0xe6,
	0x31, 0xbd, 0x84, 0x9e, 0x1e, 0x02, 0x8f, 0x21, 0xe2, 0x2b, 0xb7, 0x51, 0xc4, 0x57, 0x78, 0x06,
	0xc9, 0x7a, 0x5b, 0x14, 0xdf, 0x36, 0xba, 0xc8, 0xad, 0xa3, 0x03, 0xa6, 0x68, 0x08, 0xa7, 0x7f,
	0x5f, 0x46, 0x56, 0xe5, 0x46, 0x32, 0xba, 0x80, 0xd1, 0x4d, 0xb5, 0x0a, 0xf1, 0xcf, 0x2a, 0x57,
	0x5b, 0xe9, 0xef, 0x76, 0x0a, 0x7d, 0xc1, 0x1e, 0xc2, 0xd9, 0x2c, 0xd0, 0xd7, 0x94, 0xe6, 0x99,
	0x6b, 0xe2, 0x10, 0x1d, 0x43, 0xda, 0x44, 0xe5, 0x1a, 0xcd, 0x80, 0xbc, 0x63, 0xca, 0xa6, 0xe6,
	0x3f, 0xdf, 0x1a, 0x01, 0xfe, 0xa1, 0x0f, 0xbd, 0x86, 0x51, 0x43, 0x8d, 0x25, 0xc4, 0x19, 0x80,
	0x56, 0xc1, 0xb6, 0x21, 0x1d, 0xa3, 0x12, 0xd6, 0x55, 0x72, 0x03, 0xd4, 0x5e, 0xd1, 0x39, 0x3c,
	0x7f, 0x9f, 0xcb, 0xff, 0x33, 0xc7, 0x10, 0x62, 0x5d, 0x19, 0xac, 0xe1, 0x10, 0x7d, 0x05, 0x27,
	0x35, 0x0e, 0x37, 0xcc, 0x18, 0x92, 0x3b, 0x1f, 0x34, 0x3c, 0x47, 0xd9, 0x2e, 0x40, 0x5f, 0x03,
	0xec, 0x06, 0x0a, 0xc4, 0x5e, 0x3b, 0x87, 0x5a, 0xef, 0x5a, 0xc0, 0xc0, 0xf2, 0x5c, 0xdf, 0x7e,
	0x67, 0xcb, 0x03, 0xaa, 0xb8, 0x35, 0xa2, 0x96, 0x35, 0xba, 0xf5, 0x35, 0x6a, 0xdd, 0x7a, 0xf5,
	0x6e, 0xb3, 0x5f, 0x11, 0xb8, 0xcf, 0x09, 0x3f, 0xc0, 0xa0, 0xee, 0x19, 0x3c, 0xf3, 0xd7, 0x6d,
	0xf8, 0xc6, 0xd2, 0x71, 0x73, 0xd2, 0xa9, 0xff, 0x04, 0xbf, 0x02, 0xee, 0xbb, 0x03, 0xcf, 0x83,
	0x60, 0x6d, 0x26, 0x4c, 0xe9, 0xa1, 0x27, 0x81, 0xfe, 0x0b, 0x9c, 0xec, 0x59, 0x05, 0x27, 0xbe,
	0xb4, 0xcd, 0x79, 0xe9, 0xf9, 0x81, 0x17, 0x81, 0x7b, 0x0e, 0x49, 0x50, 0x1c, 0x89, 0xaf, 0x78,
	0x6c, 0xa4, 0x74, 0xd4, 0x90, 0xf1, 0x1c, 0xb7, 0xb1, 0xf9, 0xa7, 0xba, 0xfc, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x8e, 0x48, 0x39, 0x47, 0xb9, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PermitClient is the client API for Permit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PermitClient interface {
	CreatePermit(ctx context.Context, in *CreatePermitRequest, opts ...grpc.CallOption) (*CreatePermitResponse, error)
	UpdatePermitStatus(ctx context.Context, in *UpdatePermitStatusRequest, opts ...grpc.CallOption) (*UpdatePermitStatusResponse, error)
	GetPermitByFileID(ctx context.Context, in *GetPermitByFileIDRequest, opts ...grpc.CallOption) (*GetPermitByFileIDResponse, error)
	HasPermit(ctx context.Context, in *HasPermitRequest, opts ...grpc.CallOption) (*HasPermitResponse, error)
}

type permitClient struct {
	cc *grpc.ClientConn
}

func NewPermitClient(cc *grpc.ClientConn) PermitClient {
	return &permitClient{cc}
}

func (c *permitClient) CreatePermit(ctx context.Context, in *CreatePermitRequest, opts ...grpc.CallOption) (*CreatePermitResponse, error) {
	out := new(CreatePermitResponse)
	err := c.cc.Invoke(ctx, "/permit.permit/CreatePermit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permitClient) UpdatePermitStatus(ctx context.Context, in *UpdatePermitStatusRequest, opts ...grpc.CallOption) (*UpdatePermitStatusResponse, error) {
	out := new(UpdatePermitStatusResponse)
	err := c.cc.Invoke(ctx, "/permit.permit/UpdatePermitStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permitClient) GetPermitByFileID(ctx context.Context, in *GetPermitByFileIDRequest, opts ...grpc.CallOption) (*GetPermitByFileIDResponse, error) {
	out := new(GetPermitByFileIDResponse)
	err := c.cc.Invoke(ctx, "/permit.permit/GetPermitByFileID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permitClient) HasPermit(ctx context.Context, in *HasPermitRequest, opts ...grpc.CallOption) (*HasPermitResponse, error) {
	out := new(HasPermitResponse)
	err := c.cc.Invoke(ctx, "/permit.permit/HasPermit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermitServer is the server API for Permit service.
type PermitServer interface {
	CreatePermit(context.Context, *CreatePermitRequest) (*CreatePermitResponse, error)
	UpdatePermitStatus(context.Context, *UpdatePermitStatusRequest) (*UpdatePermitStatusResponse, error)
	GetPermitByFileID(context.Context, *GetPermitByFileIDRequest) (*GetPermitByFileIDResponse, error)
	HasPermit(context.Context, *HasPermitRequest) (*HasPermitResponse, error)
}

// UnimplementedPermitServer can be embedded to have forward compatible implementations.
type UnimplementedPermitServer struct {
}

func (*UnimplementedPermitServer) CreatePermit(ctx context.Context, req *CreatePermitRequest) (*CreatePermitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePermit not implemented")
}
func (*UnimplementedPermitServer) UpdatePermitStatus(ctx context.Context, req *UpdatePermitStatusRequest) (*UpdatePermitStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePermitStatus not implemented")
}
func (*UnimplementedPermitServer) GetPermitByFileID(ctx context.Context, req *GetPermitByFileIDRequest) (*GetPermitByFileIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPermitByFileID not implemented")
}
func (*UnimplementedPermitServer) HasPermit(ctx context.Context, req *HasPermitRequest) (*HasPermitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasPermit not implemented")
}

func RegisterPermitServer(s *grpc.Server, srv PermitServer) {
	s.RegisterService(&_Permit_serviceDesc, srv)
}

func _Permit_CreatePermit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePermitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermitServer).CreatePermit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permit.permit/CreatePermit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermitServer).CreatePermit(ctx, req.(*CreatePermitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permit_UpdatePermitStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePermitStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermitServer).UpdatePermitStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permit.permit/UpdatePermitStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermitServer).UpdatePermitStatus(ctx, req.(*UpdatePermitStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permit_GetPermitByFileID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermitByFileIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermitServer).GetPermitByFileID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permit.permit/GetPermitByFileID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermitServer).GetPermitByFileID(ctx, req.(*GetPermitByFileIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permit_HasPermit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasPermitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermitServer).HasPermit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permit.permit/HasPermit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermitServer).HasPermit(ctx, req.(*HasPermitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Permit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "permit.permit",
	HandlerType: (*PermitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePermit",
			Handler:    _Permit_CreatePermit_Handler,
		},
		{
			MethodName: "UpdatePermitStatus",
			Handler:    _Permit_UpdatePermitStatus_Handler,
		},
		{
			MethodName: "GetPermitByFileID",
			Handler:    _Permit_GetPermitByFileID_Handler,
		},
		{
			MethodName: "HasPermit",
			Handler:    _Permit_HasPermit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permit.proto",
}
