version: '3.3'
services:

  mongo_file_service:
    image: mongo:latest
    environment:
      MONGO_HOST: 'mongo_file_service'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  file_service_test:
    build:
        context: .
        dockerfile: test.Dockerfile
    environment:
      MONGO_HOST: 'mongo_file_service'
    depends_on:
      - mongo_file_service

volumes:
  mongodb_data_container:
 



