version: '2.1'
services:
  search-service:
    image: search-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SS_PORT: 8080
      SS_HOST_NAME: search-service
      SS_ELASTICSEARCH_URL: http://elasticsearch:9200
      LOG_INDEX: kdrive
      LOG_LEVEL: debug
      SS_HEALTH_CHECK_INTERVAL: 5
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_SERVICE_NAME: 'search-service'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'all'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
      SS_ELASTIC_APM_IGNORE_URLS: '/grpc.health.v1.Health/Check'
      SS_ELASTICSEARCH_INDEX: 'files'
    ports:
      - 8080:8080
    depends_on: 
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment: 
      - discovery.type=single-node
    container_name: elasticsearch
    ports: ['9200:9200']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 10s
      retries: 5
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']