version: '3.3'
services:

  minio:
    image: minio/minio
    volumes:
      - './data:/data'
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: drivetests
      MINIO_SECRET_KEY: fg4wGQOtwNNf7Yjxpt2NEBIr0c5G3++h5Qmb4NivKviy7YIum8Y24hGPl95Sj1jpLqE8LpxhpX6xmm4A4UBQ6g==
    command: server /data
  
  
  download_service_test:
    build:
        context: .
        dockerfile: test.Dockerfile
    environment:
      S3_ACCESS_KEY: drivetests
      S3_SECRET_KEY: fg4wGQOtwNNf7Yjxpt2NEBIr0c5G3++h5Qmb4NivKviy7YIum8Y24hGPl95Sj1jpLqE8LpxhpX6xmm4A4UBQ6g==
      S3_ENDPOINT: http://minio:9000
    depends_on:
      - minio