# Default values for server-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: "latest"

nameOverride: "rabbitmq"
fullnameOverride: "rabbitmq"
rabbitmqManagerPort: 15672
rabbitmqNodePort : 5672
deployment:
  health:
    enabled: true
    checks:
      livenessProbe:
        exec:
          command: ["rabbitmq-diagnostics", "check_running"]
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        exec:
          command: ["rabbitmq-diagnostics", "check_running"]
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3



ingress:
  enabled: true
  # annotations: {nginx.ingress.kubernetes.io/rewrite-target: /rabbit/$1}

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
